# Generated by Django 4.2 on 2025-04-28 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_image_profile_avatar_remove_post_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='posttranslation',
            name='is_ai_generated',
            field=models.BooleanField(default=False),
        ),
    ]
