# Generated by Django 4.2 on 2025-10-24 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_category_image_alter_post_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('admin', 'Admin'), ('editor', 'Editor'), ('author', 'Author'), ('guest', 'Guest')], max_length=20, unique=True, verbose_name='role_name')),
                ('display_name', models.CharField(max_length=50, verbose_name='role_display_name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='role_description')),
                ('can_create', models.BooleanField(default=True, verbose_name='can_create')),
                ('can_edit', models.BooleanField(default=True, verbose_name='can_edit')),
                ('can_delete', models.BooleanField(default=True, verbose_name='can_delete')),
                ('can_publish', models.BooleanField(default=True, verbose_name='can_publish')),
                ('can_manage_users', models.BooleanField(default=False, verbose_name='can_manage_users')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'role',
                'verbose_name_plural': 'roles',
                'db_table': 'api_role',
            },
        ),
        migrations.AlterModelOptions(
            name='bookmark',
            options={'verbose_name_plural': 'Bookmarks'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name_plural': 'Comments'},
        ),
        migrations.AlterModelOptions(
            name='notification',
            options={'verbose_name_plural': 'Notifications'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-date'], 'verbose_name_plural': 'Posts'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.RemoveField(
            model_name='notification',
            name='message',
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.post'),
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='api.category'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='posttranslation',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='profile',
            name='about',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.URLField(blank=True, default='default/default-user.jpg', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterModelTable(
            name='bookmark',
            table='api_bookmark',
        ),
        migrations.AlterModelTable(
            name='category',
            table='api_category',
        ),
        migrations.AlterModelTable(
            name='comment',
            table='api_comment',
        ),
        migrations.AlterModelTable(
            name='notification',
            table='api_notification',
        ),
        migrations.AlterModelTable(
            name='post',
            table='api_post',
        ),
        migrations.AlterModelTable(
            name='posttranslation',
            table='api_posttranslation',
        ),
        migrations.AlterModelTable(
            name='profile',
            table='api_profile',
        ),
        migrations.AlterModelTable(
            name='user',
            table='api_user',
        ),
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profiles', to='api.role', verbose_name='用户角色'),
        ),
    ]
