# Generated by Django 4.2 on 2025-11-02 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_role_alter_bookmark_options_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='need_ai_generate',
            field=models.BooleanField(default=False),
        ),
    ]
