# Generated by Django 4.2 on 2025-11-05 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_project_projectskill_projecttranslation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projecttranslation',
            name='form_data',
        ),
        migrations.AddField(
            model_name='project',
            name='images',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='project',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='projects', to='api.projectskill'),
        ),
        migrations.AlterField(
            model_name='projectskill',
            name='type',
            field=models.CharField(choices=[('Frontend', 'Frontend'), ('Backend', 'Backend'), ('DevOps', 'DevOps')], max_length=20),
        ),
    ]
