# Generated by Django 4.2 on 2025-11-06 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_project_is_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='projecttranslation',
            name='info',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
