# Generated by Django 4.2 on 2025-11-07 05:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_projecttranslation_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Title')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('image_url', models.URLField(max_length=500, verbose_name='Image URL')),
                ('thumbnail_url', models.URLField(blank=True, max_length=500, verbose_name='Thumbnail URL')),
                ('taken_at', models.DateTimeField(blank=True, null=True, verbose_name='Taken At')),
                ('camera_make', models.CharField(blank=True, max_length=100, verbose_name='Camera Make')),
                ('camera_model', models.CharField(blank=True, max_length=100, verbose_name='Camera Model')),
                ('lens_model', models.CharField(blank=True, max_length=100, verbose_name='Lens Model')),
                ('focal_length', models.CharField(blank=True, max_length=50, verbose_name='Focal Length')),
                ('aperture', models.CharField(blank=True, max_length=50, verbose_name='Aperture')),
                ('shutter_speed', models.CharField(blank=True, max_length=50, verbose_name='Shutter Speed')),
                ('iso', models.CharField(blank=True, max_length=50, verbose_name='ISO')),
                ('width', models.IntegerField(blank=True, null=True, verbose_name='Width')),
                ('height', models.IntegerField(blank=True, null=True, verbose_name='Height')),
                ('file_size', models.BigIntegerField(blank=True, null=True, verbose_name='File Size')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitude')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='Location')),
                ('category', models.CharField(blank=True, max_length=50, verbose_name='Category')),
                ('tags', models.JSONField(blank=True, default=list, verbose_name='Tags')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Featured')),
                ('is_published', models.BooleanField(default=True, verbose_name='Published')),
                ('view_count', models.IntegerField(default=0, verbose_name='View Count')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_photos', to=settings.AUTH_USER_MODEL, verbose_name='Uploaded By')),
            ],
            options={
                'verbose_name': 'Photo',
                'verbose_name_plural': 'Photos',
                'ordering': ['-taken_at', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='gallery',
            index=models.Index(fields=['-taken_at'], name='api_gallery_taken_a_fb5a45_idx'),
        ),
        migrations.AddIndex(
            model_name='gallery',
            index=models.Index(fields=['-created_at'], name='api_gallery_created_0e3e63_idx'),
        ),
        migrations.AddIndex(
            model_name='gallery',
            index=models.Index(fields=['is_published', 'is_featured'], name='api_gallery_is_publ_f51f6a_idx'),
        ),
    ]
