# Generated by Django 4.2 on 2025-11-07 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_gallery_gallery_api_gallery_taken_a_fb5a45_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallery',
            name='aperture',
        ),
        migrations.RemoveField(
            model_name='gallery',
            name='file_size',
        ),
        migrations.RemoveField(
            model_name='gallery',
            name='focal_length',
        ),
        migrations.RemoveField(
            model_name='gallery',
            name='height',
        ),
        migrations.RemoveField(
            model_name='gallery',
            name='iso',
        ),
        migrations.RemoveField(
            model_name='gallery',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='gallery',
            name='location',
        ),
        migrations.RemoveField(
            model_name='gallery',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='gallery',
            name='shutter_speed',
        ),
        migrations.RemoveField(
            model_name='gallery',
            name='width',
        ),
        migrations.AddField(
            model_name='gallery',
            name='location_info',
            field=models.JSONField(blank=True, default=dict, help_text='Contains latitude, longitude, location', verbose_name='Location Information'),
        ),
        migrations.AddField(
            model_name='gallery',
            name='photo_properties',
            field=models.JSONField(blank=True, default=dict, help_text='Contains width, height, file_size', verbose_name='Photo Properties'),
        ),
        migrations.AddField(
            model_name='gallery',
            name='shooting_params',
            field=models.JSONField(blank=True, default=dict, help_text='Contains focal_length, aperture, shutter_speed, iso', verbose_name='Shooting Parameters'),
        ),
    ]
