# Generated by Django 4.2 on 2025-11-08 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_remove_gallery_aperture_remove_gallery_file_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='need_ai_generate',
            field=models.BooleanField(default=True),
        ),
    ]
