# Generated by Django 4.2 on 2025-11-09 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_gallery_slug_alter_gallery_camera_make_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='slug',
            field=models.SlugField(default='', max_length=255, unique=True),
        ),
    ]
