# Generated by Django 4.2 on 2025-11-10 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_gallery_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='detail_images',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='project',
            name='github_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='live_demo_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='projecttranslation',
            name='challenges',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='projecttranslation',
            name='extra_info',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='projecttranslation',
            name='introduction',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projecttranslation',
            name='solutions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projecttranslation',
            name='subtitle',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='projecttranslation',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projecttranslation',
            name='what_i_did',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
