# Generated by Django 4.2 on 2025-11-11 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_project_detail_images_project_github_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='involved_areas',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
