# Generated by Django 4.2 on 2025-11-11 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_project_involved_areas'),
    ]

    operations = [
        migrations.AddField(
            model_name='projecttranslation',
            name='tech_summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
