# Generated by Django 4.2 on 2025-11-11 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_projecttranslation_tech_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='tools',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
