# Generated by Django 4.2 on 2025-11-11 16:24

import api.projects.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_project_tools'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projecttranslation',
            name='subtitle',
            field=models.JSONField(blank=True, default=dict, validators=[api.projects.models.validate_subtitle]),
        ),
        migrations.AlterField(
            model_name='projecttranslation',
            name='what_i_did',
            field=models.JSONField(blank=True, default=list, validators=[api.projects.models.validate_what_i_did]),
        ),
    ]
