# Generated by Django 4.2 on 2026-06-06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_alter_projecttranslation_subtitle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='priority',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
